version: "3.9"
services:
    backend:
        image: dians1container.azurecr.io/backend
        container_name: backend
        build:
            context: ./backend
        ports:
            - "8080:8080"
    frontend:
        image: dians1container.azurecr.io/frontend
        container_name: frontend
        build:
            context: ./frontend
        ports:
            - "80:3000"
        depends_on:
            - backend